import { FUND_ARTICLES, BRAND } from '@/lib/constants'
import { notFound } from 'next/navigation'
import FundArticleClient from './FundArticleClient'

export function generateStaticParams() {
  return FUND_ARTICLES.map((article) => ({ slug: article.slug }))
}

export function generateMetadata({ params }: { params: { slug: string } }) {
  const article = FUND_ARTICLES.find((a) => a.slug === params.slug)
  if (!article) return { title: 'Article Not Found' }
  return {
    title: `${article.title} | GHL India Ventures Fund Insights`,
    description: article.excerpt,
  }
}

const ARTICLE_CONTENT: Record<string, string[]> = {
  'understanding-category-ii-aifs-complete-guide': [
    'Category II Alternative Investment Funds (AIFs) represent one of the most sophisticated investment vehicles available to high-net-worth individuals (HNIs) in India. Registered under SEBI (Alternative Investment Funds) Regulations, 2012, these funds invest in unlisted securities of companies, real estate assets, distressed debt, and other alternative asset classes that are not accessible through traditional mutual funds or portfolio management services.',
    'Under SEBI\'s three-tier AIF classification, Category II AIFs occupy a unique middle ground. Unlike Category I AIFs that receive government incentives (such as venture capital or social venture funds), and Category III AIFs that employ complex trading strategies including leverage, Category II AIFs focus on medium-to-long-term capital deployment without leverage. This makes them ideal for investors seeking exposure to alternative assets with a disciplined, fundamentals-driven approach.',
    'The structural advantages of Category II AIFs are compelling for qualified investors. The pass-through tax status means that income earned by the fund is taxed in the hands of investors rather than at the fund level, avoiding the double taxation that affects many other investment structures. Capital gains treatment follows the nature and holding period of underlying investments, often resulting in more favorable tax outcomes compared to direct investments.',
    'For investors considering a Category II AIF like GHL India Ventures, the minimum ticket size of ₹1 Crore (as mandated by SEBI) reflects the institutional nature of these vehicles. The fund typically has a defined tenure of 7-10 years with provisions for extension, allowing fund managers to take a long-term view on asset resolution and value creation without the pressure of daily redemptions.',
    'Due diligence when selecting a Category II AIF should encompass several dimensions: the fund manager\'s track record and domain expertise, the investment thesis and strategy, fee structure (management fees typically range from 1.5-2.5% with carry/performance fees of 15-20%), governance framework, and the quality of the compliance and reporting infrastructure.',
    'At GHL India Ventures (SEBI Registration: IN/AIF2/2425/1517), our Category II AIF focuses exclusively on two high-conviction themes — stressed real estate resolution and early-stage startup investing in India. This dual-pillar strategy provides natural portfolio diversification, combining asset-backed investments with high-growth equity opportunities.',
    'As India\'s alternative investment industry matures, Category II AIFs are increasingly becoming the vehicle of choice for sophisticated investors who understand the risk-return trade-offs and appreciate the benefits of professional fund management, regulatory oversight, and access to institutional-grade deal flow.',
  ],
  'stressed-real-estate-india-opportunity': [
    'India\'s stressed real estate market represents a massive opportunity for disciplined investors. According to industry estimates, there are over ₹5 lakh crore worth of stressed and stalled residential projects across the country, with the National Company Law Tribunal (NCLT) and Real Estate Regulatory Authority (RERA) frameworks creating structured pathways for resolution and value recovery.',
    'Stressed real estate assets in India typically fall into three categories: stalled projects where construction has halted due to developer financial distress, Non-Performing Assets (NPAs) held by banks and NBFCs secured against real estate collateral, and distressed properties subject to NCLT proceedings under the Insolvency and Bankruptcy Code (IBC) 2016. Each category presents distinct risk-return profiles and requires specialized expertise to navigate.',
    'The NCLT resolution process has been a game-changer for stressed real estate investing. Since the introduction of the IBC, resolution professionals can acquire distressed projects at 40-70% discounts to their replacement cost. The key to success lies in identifying projects where the underlying real estate fundamentals remain strong — prime locations, existing approvals, partial construction completion, and genuine end-user demand.',
    'Chennai\'s real estate market, where GHL India Ventures is headquartered, offers particularly compelling opportunities in the stressed asset space. The city\'s robust IT/ITES sector, automotive manufacturing hub, and growing healthcare and education infrastructure create sustained demand for both residential and commercial real estate. Micro-markets like Egmore, Nungambakkam, Anna Nagar, and the OMR corridor have shown consistent absorption even during market downturns.',
    'Risk management in stressed real estate investing requires a multi-layered approach. Legal due diligence must address title clarity, encumbrance certificates, RERA registration status, environmental clearances, and any litigation history. Financial analysis must account for the cost to complete construction, working capital requirements, expected sales velocity, and realistic pricing assumptions based on comparable transactions in the micro-market.',
    'GHL India Ventures\' approach to stressed real estate follows a disciplined framework: (1) Source — identify distressed assets through banking relationships, NCLT listings, and proprietary networks; (2) Screen — apply strict filters on location quality, legal clarity, and resolution feasibility; (3) Underwrite — conduct independent valuation with conservative assumptions; (4) Acquire — negotiate optimal terms through NCLT or direct negotiation; (5) Resolve — deploy construction expertise and project management to complete and monetize the asset.',
    'For HNI investors seeking alternative investment opportunities in India, stressed real estate through a SEBI-registered Category II AIF offers asset-backed security, attractive entry valuations, and the potential for superior risk-adjusted returns over a 5-7 year investment horizon.',
  ],
  'early-stage-startups-alternative-portfolio': [
    'Early-stage startup investing has emerged as a powerful component of alternative investment portfolios for high-net-worth individuals in India. With the country producing over 100 unicorns and boasting the third-largest startup ecosystem globally, the opportunity to participate in pre-Series A and Series A funding rounds offers asymmetric return potential that traditional asset classes simply cannot match.',
    'The Indian startup ecosystem is experiencing a structural transformation driven by digital adoption, favourable demographics, and supportive government policies like Startup India. Sectors such as fintech, healthtech, edtech, SaaS, agritech, and clean energy are seeing tremendous innovation, with startups solving uniquely Indian problems at massive scale. For AIF investors, this translates into a broad universe of investable opportunities across sectors and stages.',
    'Early-stage investing through a structured AIF vehicle offers several advantages over direct angel investing. Professional due diligence, portfolio diversification across 10-15 companies, ongoing portfolio management, governance support, and follow-on investment capabilities reduce the idiosyncratic risks that plague individual angel investments. The AIF structure also provides regulatory clarity and investor protection under SEBI\'s oversight.',
    'At GHL India Ventures, our startup investment thesis focuses on four key criteria: (1) Strong founding teams with domain expertise and complementary skill sets; (2) Clear product-market fit demonstrated through early revenue traction or validated demand; (3) Unit economics that show a credible path to profitability; and (4) Addressable markets large enough to support venture-scale outcomes.',
    'Our proprietary deal flow pipeline, built through deep engagement with Chennai\'s startup ecosystem, relationships with accelerators like Startup Village, CII, and NASSCOM, and pan-India venture networks, gives us access to high-conviction opportunities before they reach the broader market. We evaluate over 200 startups annually to invest in 3-5 that meet our rigorous selection criteria.',
    'Portfolio construction in early-stage startup investing follows a power-law distribution — a small number of investments typically drive the majority of returns. Understanding this dynamic, we construct portfolios designed to capture outsized returns from winners while managing downside through disciplined entry valuations, milestone-based funding, and active board participation.',
    'For sophisticated investors with a risk appetite for high-growth alternative assets, allocating a portion of their AIF investment to early-stage startups through a SEBI-registered fund like GHL India Ventures provides institutional-grade access to India\'s innovation economy with professional risk management and regulatory compliance.',
  ],
  'sebi-aif-framework-sophisticated-investor': [
    'The Securities and Exchange Board of India (SEBI) established a comprehensive regulatory framework for Alternative Investment Funds through SEBI (Alternative Investment Funds) Regulations, 2012. This framework governs the registration, operation, and compliance requirements for all AIFs operating in India, providing institutional investors and HNIs with the regulatory assurance necessary for committing significant capital to alternative asset classes.',
    'SEBI classifies AIFs into three categories, each with distinct investment mandates and regulatory requirements. Category I AIFs include venture capital funds, social venture funds, SME funds, and infrastructure funds that invest in start-ups and early-stage ventures with positive spillover effects. Category II AIFs, such as GHL India Ventures, invest in unlisted securities and real estate without employing leverage. Category III AIFs include hedge funds and other funds that employ diverse or complex trading strategies.',
    'Registration requirements under SEBI\'s AIF framework mandate a minimum corpus of ₹20 crore (₹10 crore for angel funds), with each investor contributing a minimum of ₹1 crore. The fund manager must have adequate infrastructure, key investment team members with relevant experience, and a clearly defined investment strategy. SEBI reviews applications for the quality of the team, the soundness of the investment thesis, and the adequacy of risk management and compliance frameworks.',
    'Compliance obligations for registered AIFs are rigorous and ongoing. Funds must file quarterly reports to SEBI covering portfolio composition, NAV, investor details, and any material changes. Annual audited financial statements must be submitted, and any changes to the fund\'s operating agreement or investment strategy require prior SEBI approval. Anti-money laundering (AML) and Know Your Customer (KYC) compliance is mandatory for all investor onboarding.',
    'Investor protection under the SEBI AIF framework includes several key provisions: mandatory custodian appointment for asset safekeeping, independent valuation of portfolio assets, conflict of interest disclosure requirements, prohibition on guaranteed returns, and strict guidelines on fee transparency. These provisions ensure that investor interests are protected throughout the fund\'s lifecycle.',
    'Tax treatment for Category II AIFs operates on a pass-through basis, meaning the fund itself is not taxed — instead, income and gains are attributed to investors and taxed in their hands. This avoids the double taxation that can erode returns in other structures. Long-term capital gains on unlisted securities held for more than 24 months are taxed at 20% with indexation benefits, providing meaningful tax efficiency for patient investors.',
    'GHL India Ventures Trust (Registration No. IN/AIF2/2425/1517) operates as a SEBI-registered Category II AIF with full compliance across all regulatory requirements. Our commitment to transparency, governance, and investor protection goes beyond minimum regulatory mandates, reflecting our belief that trust is the foundation of long-term investment partnerships.',
  ],
  'portfolio-diversification-beyond-mutual-funds': [
    'Traditional portfolio diversification through mutual funds, while suitable for most retail investors, often falls short for high-net-worth individuals seeking truly uncorrelated returns and exposure to alternative asset classes. Category II Alternative Investment Funds (AIFs) bridge this gap by providing access to institutional-grade investments in unlisted securities, real estate, and other alternative assets that are simply not available through conventional investment channels.',
    'The correlation between mutual fund returns and broad equity market indices (Nifty 50, Sensex) remains persistently high, typically above 0.85 for equity-oriented schemes. This means that during market downturns, mutual fund portfolios tend to decline in lockstep with the broader market, negating much of the diversification benefit. Alternative investments through AIFs, by contrast, often exhibit low or negative correlation with listed equity markets, providing genuine portfolio diversification.',
    'Real estate-focused AIF strategies, such as GHL India Ventures\' stressed real estate vertical, offer asset-backed returns that are structurally different from equity market returns. The value creation in stressed real estate comes from resolution — acquiring distressed assets at deep discounts and restoring them to productive use — rather than from market sentiment or earnings multiples. This resolution-driven return profile provides natural hedging against equity market volatility.',
    'Early-stage startup investments within an AIF portfolio add a high-growth, high-innovation dimension that traditional asset classes cannot replicate. While individual startup investments carry higher risk, a professionally managed portfolio of 10-15 early-stage companies can deliver exceptional returns through the power-law dynamics of venture investing, where a small number of winners generate outsized returns.',
    'The optimal portfolio allocation to alternative investments varies by investor profile, but research consistently shows that a 10-25% allocation to alternatives significantly improves the risk-adjusted return profile of a diversified portfolio. For Indian HNIs with portfolios exceeding ₹5 crore, a ₹1 crore allocation to a Category II AIF represents a prudent step toward true portfolio diversification.',
    'Fee structures in AIFs typically include management fees (1.5-2.5% annually) and performance fees (15-20% above a hurdle rate). While these are higher than mutual fund expense ratios, the value proposition is fundamentally different — AIFs provide active management, proprietary deal flow, operational value creation, and access to asset classes that cannot be accessed through passive or low-cost vehicles.',
    'At GHL India Ventures, our dual-focus strategy across stressed real estate and early-stage startups is specifically designed to deliver uncorrelated, risk-adjusted returns for our investors. By combining asset-backed real estate with high-growth startup exposure within a single SEBI-registered AIF, we offer a comprehensive alternative investment solution for discerning HNIs.',
  ],
  'chennai-real-estate-data-driven-thesis-2025': [
    'Chennai\'s real estate market stands at an inflection point in 2025, driven by robust infrastructure development, expanding IT/ITES footprint, and improving connectivity that is reshaping the city\'s residential and commercial corridors. For investors in stressed real estate through Category II AIFs like GHL India Ventures, understanding the data-driven fundamentals of Chennai\'s micro-markets is essential for identifying high-conviction investment opportunities.',
    'The city\'s residential market has shown remarkable resilience, with new launch volumes increasing 22% year-over-year in 2024 and absorption rates hitting a five-year high. Key micro-markets such as OMR (Old Mahabalipuram Road), Porur-Manapakkam, Perambur-Kolathur, and Tambaram-Chromepet are witnessing strong demand from both end-users and investors. Notably, the premium segment (₹1 crore+) has outperformed, growing 35% in transaction volume.',
    'Chennai\'s commercial real estate fundamentals remain among the strongest in India. The city is the second-largest IT/ITES hub after Bengaluru, with over 70 million square feet of Grade-A office space. Vacancy rates in prime corridors like Guindy, RR Nagar, and OMR have dropped below 8%, and rental values have appreciated 12-15% over the past two years. The upcoming Metro Phase 2 expansion and the Chennai Peripheral Ring Road are expected to unlock significant value in peripheral markets.',
    'The stressed real estate opportunity in Chennai is concentrated in specific pockets where developer distress has created acquisition opportunities at 40-60% below replacement cost. GHL India Ventures has identified over 25 potentially viable stressed projects in the Chennai Metropolitan Area, primarily in premium locations like Egmore, Nungambakkam, T. Nagar, and Anna Nagar where underlying demand remains strong despite project-level distress.',
    'Infrastructure mega-projects are reshaping Chennai\'s real estate landscape. The ₹61,843 crore Chennai Metro Phase 2, the ₹10,000 crore Chennai Peripheral Ring Road, the new international airport terminal expansion, and the Chennai-Bengaluru Industrial Corridor are creating new growth corridors and enhancing connectivity in existing ones. These developments create tailwinds for both stressed asset resolution and new project appreciation.',
    'RERA implementation in Tamil Nadu has brought much-needed transparency to Chennai\'s real estate market, with over 5,000 projects registered. For stressed asset investors, RERA compliance provides regulatory certainty, ensures project accountability, and protects the interests of existing homebuyers in revived projects. Our investment framework explicitly requires RERA compliance as a prerequisite for any acquisition.',
    'GHL India Ventures\' Chennai-first strategy leverages our deep local knowledge, established banking and legal networks, and hands-on project management capabilities to create value in the city\'s stressed real estate market. As Chennai continues its trajectory as a global city with a $100 billion GDP target by 2030, we believe patient capital deployed in carefully selected stressed assets today will deliver compelling returns over the next 5-7 years.',
  ],
  'due-diligence-startup-investments-ghl-framework': [
    'Due diligence in early-stage startup investing is fundamentally different from traditional financial analysis. At the pre-Series A and Series A stages where GHL India Ventures deploys capital, startups often have limited financial history but significant potential. Our proprietary 7-layer due diligence framework is designed to systematically evaluate this potential while identifying and mitigating risks that could derail an otherwise promising investment.',
    'Layer 1 — Team Assessment: We evaluate the founding team across five dimensions — domain expertise, complementary skill sets, execution track record, resilience quotient, and coachability. Our experience shows that the quality of the founding team is the single most important predictor of startup success at the early stage, accounting for over 60% of our investment decision weighting.',
    'Layer 2 — Market Analysis: We assess the total addressable market (TAM), serviceable addressable market (SAM), and the startup\'s realistic serviceable obtainable market (SOM) over a 5-year horizon. We particularly favour startups addressing uniquely Indian market needs with solutions that can scale across the country\'s diverse demographic and geographic landscape.',
    'Layer 3 — Product & Technology: We evaluate the product\'s technical architecture, scalability, competitive moats (proprietary technology, network effects, data advantages), and user experience. For deep-tech startups, we engage domain experts from our advisory network to assess the viability and defensibility of the underlying technology.',
    'Layer 4 — Unit Economics: Even at early stages, we look for clear evidence of positive unit economics or a credible path to achieving them. Key metrics include Customer Acquisition Cost (CAC), Lifetime Value (LTV), gross margins, burn rate, and the LTV/CAC ratio. Startups with LTV/CAC ratios above 3x and clear paths to contribution margin positivity receive priority in our investment pipeline.',
    'Layer 5 — Financial & Legal: We conduct thorough financial due diligence covering cap table analysis, previous funding terms, outstanding obligations, and financial projections. Legal due diligence covers corporate governance, IP ownership, employment agreements, regulatory compliance, and any pending or potential litigation. This layer often reveals hidden risks that are not apparent from surface-level analysis.',
    'Layer 6 — Governance & Risk: We assess the startup\'s governance framework, board composition, information rights, and risk management practices. For our AIF investors, strong governance at the portfolio company level is non-negotiable — it protects their capital and ensures alignment of interests between founders and investors.',
  ],
  'tax-efficiency-category-ii-aif-pass-through': [
    'Tax efficiency is a critical consideration for high-net-worth individuals evaluating Alternative Investment Fund (AIF) investments. Category II AIFs enjoy pass-through status under Indian tax law, meaning the fund itself is not treated as a separate taxable entity. Instead, income earned by the fund is attributed to investors and taxed in their hands based on the nature of the income and their individual tax profiles.',
    'The pass-through mechanism works differently for different types of income. Business income earned by the fund is taxed at the fund level and then distributed as exempt income to investors. However, capital gains, dividends, and interest income pass through directly to investors and are taxed based on the holding period and nature of the underlying investments. This distinction is crucial for optimizing after-tax returns.',
    'For unlisted equity investments held for more than 24 months (typical for both stressed real estate SPVs and startup equity), long-term capital gains are taxed at 20% with indexation benefits. This provides significant tax efficiency compared to business income tax rates of 30%+. Structuring investments to qualify for long-term capital gains treatment is a key consideration in GHL India Ventures\' investment strategy.',
    'Real estate investments within the AIF structure offer additional tax advantages. When the fund invests through Special Purpose Vehicles (SPVs) — which is standard practice for stressed real estate acquisitions — the sale of SPV equity after 24 months qualifies for long-term capital gains treatment. This is more tax-efficient than direct real estate transactions, which attract separate stamp duty, registration charges, and capital gains tax.',
    'TDS (Tax Deducted at Source) implications vary by income type. The fund deducts TDS at 10% on income distributions to resident investors. Investors can claim credit for this TDS in their annual tax returns. For NRI investors, TDS rates may differ, and Double Taxation Avoidance Agreements (DTAAs) may provide relief depending on the investor\'s country of residence.',
    'Annual compliance for AIF investors is relatively straightforward. The fund provides annual statements detailing income attribution, capital gains, and TDS certificates. Investors include these amounts in their individual tax returns. The fund administrator ensures accurate computation and timely issuance of tax statements to all investors.',
    'At GHL India Ventures, we work closely with leading tax advisors to structure our investments in the most tax-efficient manner for our Category II AIF investors. Our fund administrator provides comprehensive annual tax packs, and our investor relations team is available to coordinate with investors\' tax advisors for seamless compliance.',
  ],
  'risk-adjusted-returns-alternative-investments': [
    'Risk-adjusted returns are the true measure of investment performance, separating genuinely skilled fund managers from those merely riding market beta. For high-net-worth investors evaluating Alternative Investment Funds (AIFs), understanding risk-adjusted metrics like the Sharpe ratio, Sortino ratio, and maximum drawdown is essential for making informed allocation decisions.',
    'Traditional asset classes in India have delivered strong nominal returns over the past decade — Nifty 50 has compounded at approximately 12-14% CAGR, while fixed deposits have yielded 5-7%. However, when adjusted for risk (volatility), the picture changes significantly. The Nifty 50\'s Sharpe ratio has averaged 0.6-0.8, reflecting the substantial volatility that equity investors must endure to capture those returns.',
    'Alternative investments through Category II AIFs can offer meaningfully different risk-return profiles. Stressed real estate investments, for instance, have an inherent "margin of safety" built in through discounted acquisition prices. When assets are acquired at 40-60% below replacement cost through NCLT processes, the downside risk is structurally limited while the upside from resolution and market recovery can be substantial.',
    'The drawdown profile of alternative investments is particularly attractive for wealth preservation-focused HNIs. During the 2020 COVID-19 market crash, listed equity portfolios experienced 30-40% peak-to-trough drawdowns. Well-structured AIF portfolios with stressed real estate and pre-revenue startup investments experienced significantly lower mark-to-market volatility, as these assets are valued based on fundamental metrics rather than daily market sentiment.',
    'Portfolio construction within an AIF should aim for optimal diversification across risk factors. At GHL India Ventures, our dual-pillar strategy combines stressed real estate (lower volatility, asset-backed, resolution-driven returns) with early-stage startups (higher volatility, higher potential returns, growth-driven). This combination targets a portfolio-level Sharpe ratio significantly above what either strategy would deliver in isolation.',
    'Performance benchmarking for AIFs should consider both absolute returns and risk-adjusted metrics over the full fund lifecycle. Unlike listed equity where daily NAV comparison is meaningful, AIF performance is best evaluated at maturity or through interim metrics like MOIC (Multiple on Invested Capital), IRR (Internal Rate of Return), and DPI (Distributions to Paid-In capital).',
    'For investors seeking superior risk-adjusted returns beyond what traditional mutual funds and PMS strategies can deliver, SEBI-registered Category II AIFs like GHL India Ventures offer a compelling proposition: access to alternative asset classes, professional risk management, and the potential for uncorrelated returns that genuinely diversify a well-constructed wealth portfolio.',
  ],
  'building-long-term-wealth-10-year-aif-case': [
    'The most successful investors in history share one common trait: patience. Building long-term wealth requires a willingness to commit capital over extended timeframes, allowing the power of compounding and value creation to work in your favour. A 10-year investment horizon through a Category II Alternative Investment Fund (AIF) aligns perfectly with this philosophy, providing the time needed for stressed real estate resolution and startup maturation.',
    'The mathematics of long-term compounding in alternative investments are compelling. An investment of ₹1 Crore growing at 18-22% IRR (a realistic target for a well-managed diversified AIF) over 10 years results in a corpus of ₹5.2-7.3 Crore. This represents a 5-7x multiple on invested capital (MOIC) — returns that are difficult to achieve consistently through traditional asset classes over the same period.',
    'Stressed real estate investments typically require 3-5 years for full resolution — from acquisition through NCLT, construction completion, regulatory approvals, sales, and exit. A 10-year fund tenure allows for 2-3 investment cycles, enabling the fund to compound returns by redeploying proceeds from early exits into new opportunities. This recycling of capital significantly enhances overall fund returns.',
    'Early-stage startup investments follow a different but equally compelling trajectory. The typical path from seed/pre-Series A investment to a meaningful exit (through IPO, strategic acquisition, or secondary sale) takes 5-8 years. A 10-year fund tenure provides adequate runway for portfolio companies to reach maturity without the pressure of premature exits that can destroy value.',
    'Market cycles work in favour of patient AIF investors. India\'s economy is projected to grow from $3.7 trillion to over $7 trillion in GDP by 2030, with real estate and technology sectors expected to be major beneficiaries. Investors who commit capital today through a structured AIF vehicle are positioning themselves to capture this structural growth over the coming decade.',
    'The behavioural advantage of locked-in capital in an AIF cannot be overstated. Unlike liquid investments where emotional decision-making often leads to buying high and selling low, the committed capital structure of an AIF prevents investors from making impulsive decisions during market volatility. This enforced patience has historically been one of the most powerful drivers of superior long-term returns.',
    'At GHL India Ventures, we believe that wealth creation is a marathon, not a sprint. Our Category II AIF is structured with a base tenure that allows us to take a long-term view on every investment, optimise exit timing for maximum value realisation, and compound returns for our investors. For qualified HNIs with appropriate risk tolerance and a decade-long perspective, we offer a disciplined pathway to building lasting, generational wealth.',
  ],
}

export default function FundArticlePage({ params }: { params: { slug: string } }) {
  const article = FUND_ARTICLES.find((a) => a.slug === params.slug)
  if (!article) notFound()

  // Unique article content per slug, with generic fallback
  const content = ARTICLE_CONTENT[params.slug] || [
    `This article explores important aspects of alternative investing that every sophisticated investor should understand. At GHL India Ventures, we believe that informed investors make better investment decisions, which is why we produce educational content spanning stressed real estate, startup investing, regulatory frameworks, and portfolio construction strategies.`,
  ]

  // Get 3 related articles (excluding current)
  const relatedArticles = FUND_ARTICLES.filter((a) => a.slug !== params.slug).slice(0, 3)

  return (
    <FundArticleClient
      article={article}
      content={content}
      relatedArticles={relatedArticles}
      sebiReg={BRAND.sebi}
    />
  )
}
