/* ================================================================
   STAFF PORTAL — MOCK DATA
   GHL India Ventures Private Limited
   ================================================================ */

import type {
  StaffEmployee,
  AttendanceRecord,
  LeaveBalance,
  LeaveApplication,
  Payslip,
  CSKPIs,
  Ticket,
  ClientInteraction,
  QueueItem,
  StaffTask,
  FieldCheckIn,
  SiteVisit,
  FieldProspect,
  FieldExpense,
  StaffAITool,
  KBArticle,
  Announcement,
  TrainingModule,
} from './staffTypes'

// ── 1. Staff Employees ──────────────────────────────────────────
export const STAFF_EMPLOYEES: StaffEmployee[] = [
  {
    id: 'emp-001',
    staffCode: 'GHL001',
    name: 'Arvind Krishnamurthy',
    email: 'arvind.k@ghlindia.com',
    phone: '+91 98401 23456',
    designation: 'Customer Success Lead',
    department: 'Customer Success',
    role: 'cs-lead',
    reportingTo: 'Rajesh Venkataraman',
    joinDate: '2021-03-15',
    status: 'active',
    skills: ['Team Leadership', 'Conflict Resolution', 'AIF Regulations', 'CRM'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-002',
    staffCode: 'GHL004',
    name: 'Priya Venkatesh',
    email: 'priya.v@ghlindia.com',
    phone: '+91 98402 34567',
    designation: 'Senior CS Agent',
    department: 'Customer Success',
    role: 'senior-cs-agent',
    reportingTo: 'Arvind Krishnamurthy',
    joinDate: '2022-01-10',
    status: 'active',
    skills: ['Escalation Handling', 'KYC Compliance', 'Client Retention', 'SEBI Norms'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-003',
    staffCode: 'GHL007',
    name: 'Karthik Subramanian',
    email: 'karthik.s@ghlindia.com',
    phone: '+91 98403 45678',
    designation: 'CS Agent',
    department: 'Customer Success',
    role: 'cs-agent',
    reportingTo: 'Arvind Krishnamurthy',
    joinDate: '2023-06-20',
    status: 'active',
    skills: ['Chat Support', 'Email Handling', 'NAV Queries'],
    location: 'Chennai - T. Nagar Office',
    shift: 'Morning (8:00 AM - 5:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-004',
    staffCode: 'GHL009',
    name: 'Deepa Ramanathan',
    email: 'deepa.r@ghlindia.com',
    phone: '+91 98404 56789',
    designation: 'CS Agent',
    department: 'Customer Success',
    role: 'cs-agent',
    reportingTo: 'Arvind Krishnamurthy',
    joinDate: '2023-09-01',
    status: 'probation',
    skills: ['WhatsApp Support', 'Document Verification', 'Basic KYC'],
    location: 'Chennai - T. Nagar Office',
    shift: 'Afternoon (12:00 PM - 9:00 PM)',
    isOnline: false,
  },
  {
    id: 'emp-005',
    staffCode: 'GHL012',
    name: 'Manoj Kumar Pillai',
    email: 'manoj.p@ghlindia.com',
    phone: '+91 98405 67890',
    designation: 'CS Agent',
    department: 'Customer Success',
    role: 'cs-agent',
    reportingTo: 'Priya Venkatesh',
    joinDate: '2024-02-15',
    status: 'active',
    skills: ['Call Handling', 'Complaint Resolution', 'CRM Tools'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-006',
    staffCode: 'GHL015',
    name: 'Lakshmi Narayanan',
    email: 'lakshmi.n@ghlindia.com',
    phone: '+91 98406 78901',
    designation: 'Relationship Manager',
    department: 'Relationship Management',
    role: 'relationship-manager',
    reportingTo: 'Rajesh Venkataraman',
    joinDate: '2022-05-01',
    status: 'active',
    skills: ['HNI Client Management', 'Portfolio Advisory', 'Investment Products', 'Networking'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-007',
    staffCode: 'GHL018',
    name: 'Suresh Balakrishnan',
    email: 'suresh.b@ghlindia.com',
    phone: '+91 98407 89012',
    designation: 'Relationship Manager',
    department: 'Relationship Management',
    role: 'relationship-manager',
    reportingTo: 'Rajesh Venkataraman',
    joinDate: '2023-01-15',
    status: 'active',
    skills: ['NRI Clients', 'AIF Structuring', 'Tax Planning', 'Client Onboarding'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: false,
  },
  {
    id: 'emp-008',
    staffCode: 'GHL020',
    name: 'Rajesh Chandrasekaran',
    email: 'rajesh.c@ghlindia.com',
    phone: '+91 98408 90123',
    designation: 'Field Sales Manager',
    department: 'Field Sales',
    role: 'field-sales-manager',
    reportingTo: 'Rajesh Venkataraman',
    joinDate: '2021-08-01',
    status: 'active',
    skills: ['Team Management', 'Business Development', 'Investor Relations', 'Market Analysis'],
    location: 'Chennai - Anna Nagar Office',
    shift: 'Flexible (Field)',
    isOnline: true,
  },
  {
    id: 'emp-009',
    staffCode: 'GHL024',
    name: 'Arun Prakash',
    email: 'arun.p@ghlindia.com',
    phone: '+91 98409 01234',
    designation: 'Field Sales Executive',
    department: 'Field Sales',
    role: 'field-sales-executive',
    reportingTo: 'Rajesh Chandrasekaran',
    joinDate: '2023-04-10',
    status: 'active',
    skills: ['Site Visits', 'Cold Calling', 'Investor Pitching', 'CRM'],
    location: 'Chennai - Anna Nagar Office',
    shift: 'Flexible (Field)',
    isOnline: true,
  },
  {
    id: 'emp-010',
    staffCode: 'GHL027',
    name: 'Divya Shanmugam',
    email: 'divya.s@ghlindia.com',
    phone: '+91 98410 12345',
    designation: 'Field Sales Executive',
    department: 'Field Sales',
    role: 'field-sales-executive',
    reportingTo: 'Rajesh Chandrasekaran',
    joinDate: '2024-01-08',
    status: 'active',
    skills: ['Client Prospecting', 'Presentation Skills', 'Real Estate Knowledge'],
    location: 'Bangalore - Koramangala Office',
    shift: 'Flexible (Field)',
    isOnline: false,
  },
  {
    id: 'emp-011',
    staffCode: 'GHL030',
    name: 'Vijay Anand',
    email: 'vijay.a@ghlindia.com',
    phone: '+91 98411 23456',
    designation: 'Site Inspector',
    department: 'Operations',
    role: 'site-inspector',
    reportingTo: 'Rajesh Chandrasekaran',
    joinDate: '2022-11-01',
    status: 'active',
    skills: ['Construction Assessment', 'Due Diligence', 'Photography', 'Report Writing'],
    location: 'Chennai - Anna Nagar Office',
    shift: 'Flexible (Field)',
    isOnline: true,
  },
  {
    id: 'emp-012',
    staffCode: 'GHL035',
    name: 'Meenakshi Sundaram',
    email: 'meenakshi.s@ghlindia.com',
    phone: '+91 98412 34567',
    designation: 'KYC Officer',
    department: 'Compliance',
    role: 'kyc-officer',
    reportingTo: 'Arvind Krishnamurthy',
    joinDate: '2022-07-15',
    status: 'active',
    skills: ['KYC/AML', 'SEBI Compliance', 'Document Verification', 'Risk Assessment'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-013',
    staffCode: 'GHL040',
    name: 'Ganesh Ramamurthy',
    email: 'ganesh.r@ghlindia.com',
    phone: '+91 98413 45678',
    designation: 'Operations Executive',
    department: 'Operations',
    role: 'operations-executive',
    reportingTo: 'Arvind Krishnamurthy',
    joinDate: '2023-03-01',
    status: 'active',
    skills: ['Process Management', 'Vendor Coordination', 'Reporting', 'Data Entry'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-014',
    staffCode: 'GHL045',
    name: 'Sowmya Parthasarathy',
    email: 'sowmya.p@ghlindia.com',
    phone: '+91 98414 56789',
    designation: 'HR Executive',
    department: 'Human Resources',
    role: 'hr-executive',
    reportingTo: 'Rajesh Venkataraman',
    joinDate: '2022-09-01',
    status: 'active',
    skills: ['Recruitment', 'Payroll', 'Employee Engagement', 'Labour Law'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: true,
  },
  {
    id: 'emp-015',
    staffCode: 'GHL050',
    name: 'Balaji Srinivasan',
    email: 'balaji.s@ghlindia.com',
    phone: '+91 98415 67890',
    designation: 'Office Coordinator',
    department: 'Administration',
    role: 'general-employee',
    reportingTo: 'Sowmya Parthasarathy',
    joinDate: '2024-06-01',
    status: 'probation',
    skills: ['Office Management', 'Scheduling', 'Inventory'],
    location: 'Chennai - T. Nagar Office',
    shift: 'General (9:00 AM - 6:00 PM)',
    isOnline: false,
  },
]

// ── 2. Attendance Data ──────────────────────────────────────────
export const MY_ATTENDANCE_DATA: AttendanceRecord[] = [
  { date: '2026-02-01', status: 'weekend' },
  { date: '2026-02-02', clockIn: '09:02', clockOut: '18:15', totalHours: 8.72, breakDuration: 45, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-03', clockIn: '09:10', clockOut: '18:05', totalHours: 8.42, breakDuration: 50, status: 'present', lateArrival: true, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-04', clockIn: '08:55', clockOut: '18:30', totalHours: 9.08, breakDuration: 45, status: 'present', lateArrival: false, overtime: 0.58, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-05', clockIn: '09:00', clockOut: '18:00', totalHours: 8.5, breakDuration: 30, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-06', clockIn: '09:05', clockOut: '18:20', totalHours: 8.75, breakDuration: 40, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-07', status: 'weekend' },
  { date: '2026-02-08', status: 'weekend' },
  { date: '2026-02-09', clockIn: '09:00', clockOut: '18:10', totalHours: 8.67, breakDuration: 45, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-10', status: 'leave' },
  { date: '2026-02-11', status: 'leave' },
  { date: '2026-02-12', clockIn: '09:15', clockOut: '18:00', totalHours: 8.25, breakDuration: 45, status: 'present', lateArrival: true, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-13', clockIn: '09:00', clockOut: '13:00', totalHours: 3.5, breakDuration: 30, status: 'half-day', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-14', status: 'weekend' },
  { date: '2026-02-15', status: 'weekend' },
  { date: '2026-02-16', clockIn: '08:50', clockOut: '18:25', totalHours: 9.08, breakDuration: 45, status: 'present', lateArrival: false, overtime: 0.58, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-17', clockIn: '09:00', clockOut: '18:00', totalHours: 8.5, breakDuration: 30, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-18', clockIn: '09:05', clockOut: '18:10', totalHours: 8.58, breakDuration: 40, status: 'present', lateArrival: false, location: 'Chennai - T. Nagar Office' },
  { date: '2026-02-19', status: 'holiday' },
  { date: '2026-02-20', clockIn: '08:58', clockOut: '18:30', totalHours: 9.03, breakDuration: 45, status: 'present', lateArrival: false, overtime: 0.53, location: 'Chennai - T. Nagar Office' },
]

// ── 3. Leave Balances ───────────────────────────────────────────
export const MY_LEAVE_BALANCES: LeaveBalance[] = [
  { type: 'casual', total: 12, used: 4, pending: 1, available: 7 },
  { type: 'sick', total: 8, used: 2, pending: 0, available: 6 },
  { type: 'earned', total: 15, used: 5, pending: 2, available: 8 },
  { type: 'comp-off', total: 3, used: 1, pending: 0, available: 2 },
  { type: 'loss-of-pay', total: 0, used: 0, pending: 0, available: 0 },
]

// ── 4. Leave History ────────────────────────────────────────────
export const MY_LEAVE_HISTORY: LeaveApplication[] = [
  {
    id: 'leave-001',
    type: 'casual',
    fromDate: '2026-02-10',
    toDate: '2026-02-11',
    days: 2,
    reason: 'Family function - sister wedding ceremony in Madurai',
    status: 'approved',
    appliedDate: '2026-02-03',
    approvedBy: 'Arvind Krishnamurthy',
  },
  {
    id: 'leave-002',
    type: 'sick',
    fromDate: '2026-01-20',
    toDate: '2026-01-21',
    days: 2,
    reason: 'Fever and cold - doctor advised rest',
    status: 'approved',
    appliedDate: '2026-01-20',
    approvedBy: 'Arvind Krishnamurthy',
    attachment: 'medical-certificate-jan2026.pdf',
  },
  {
    id: 'leave-003',
    type: 'earned',
    fromDate: '2026-03-02',
    toDate: '2026-03-04',
    days: 3,
    reason: 'Personal trip to Kerala with family',
    status: 'pending',
    appliedDate: '2026-02-18',
  },
  {
    id: 'leave-004',
    type: 'casual',
    fromDate: '2026-02-13',
    toDate: '2026-02-13',
    days: 0.5,
    halfDay: true,
    reason: 'Dental appointment in the afternoon',
    status: 'approved',
    appliedDate: '2026-02-11',
    approvedBy: 'Arvind Krishnamurthy',
  },
  {
    id: 'leave-005',
    type: 'comp-off',
    fromDate: '2025-12-29',
    toDate: '2025-12-29',
    days: 1,
    reason: 'Comp-off against working on Saturday 20th December for year-end closing',
    status: 'approved',
    appliedDate: '2025-12-22',
    approvedBy: 'Arvind Krishnamurthy',
  },
  {
    id: 'leave-006',
    type: 'earned',
    fromDate: '2026-04-14',
    toDate: '2026-04-16',
    days: 2,
    reason: 'Tamil New Year celebrations and travel to native place',
    status: 'rejected',
    appliedDate: '2026-02-20',
    approvedBy: 'Arvind Krishnamurthy',
  },
]

// ── 5. Payslips ─────────────────────────────────────────────────
export const MY_PAYSLIPS: Payslip[] = [
  {
    id: 'pay-2026-01',
    month: 'January',
    year: 2026,
    basic: 25000,
    hra: 12500,
    specialAllowance: 8000,
    conveyance: 1600,
    medical: 1250,
    pfEmployee: 3000,
    pfEmployer: 3000,
    esi: 750,
    professionalTax: 200,
    tds: 2500,
    grossEarnings: 48350,
    totalDeductions: 6450,
    netSalary: 41900,
    paymentDate: '2026-01-31',
  },
  {
    id: 'pay-2025-12',
    month: 'December',
    year: 2025,
    basic: 25000,
    hra: 12500,
    specialAllowance: 8000,
    conveyance: 1600,
    medical: 1250,
    pfEmployee: 3000,
    pfEmployer: 3000,
    esi: 750,
    professionalTax: 200,
    tds: 2500,
    grossEarnings: 48350,
    totalDeductions: 6450,
    netSalary: 41900,
    paymentDate: '2025-12-31',
  },
  {
    id: 'pay-2025-11',
    month: 'November',
    year: 2025,
    basic: 25000,
    hra: 12500,
    specialAllowance: 8000,
    conveyance: 1600,
    medical: 1250,
    pfEmployee: 3000,
    pfEmployer: 3000,
    esi: 750,
    professionalTax: 200,
    tds: 2200,
    grossEarnings: 48350,
    totalDeductions: 6150,
    netSalary: 42200,
    paymentDate: '2025-11-30',
  },
]

// ── 6. CS KPIs ──────────────────────────────────────────────────
export const CS_KPIS_DATA: CSKPIs = {
  ticketsResolved: 23,
  avgResponseTime: 45,
  csatScore: 4.6,
  callsHandled: 18,
  chatsHandled: 34,
  firstCallResolution: 78,
  queueWaitTime: 32,
  activeTickets: 12,
  escalations: 3,
  totalInteractions: 52,
}

// ── 7. Tickets ──────────────────────────────────────────────────
export const TICKETS_DATA: Ticket[] = [
  {
    id: 'TKT-1001',
    clientId: 'cli-101',
    clientName: 'Raghunath Iyer',
    subject: 'NAV discrepancy in AIF Category III fund',
    description: 'Investor has observed a mismatch between the NAV shown on the portal and the NAV communicated via email for the month of January 2026.',
    category: 'nav',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'emp-003',
    assignedToName: 'Karthik Subramanian',
    createdDate: '2026-02-18T09:30:00',
    updatedDate: '2026-02-20T14:15:00',
    channel: 'email',
    escalationLevel: 1,
    messages: [
      { id: 'msg-1001-1', sender: 'Raghunath Iyer', senderType: 'client', message: 'I noticed my AIF Cat III NAV is showing 118.45 on the portal but the email dated 15th Jan shows 119.02. Kindly clarify this discrepancy at the earliest.', timestamp: '2026-02-18T09:30:00' },
      { id: 'msg-1001-2', sender: 'Karthik Subramanian', senderType: 'agent', message: 'Thank you for bringing this to our notice, Mr. Iyer. We are checking with the fund accounting team. The portal NAV gets updated with a T+1 lag. We will revert with a detailed explanation shortly.', timestamp: '2026-02-18T10:15:00' },
      { id: 'msg-1001-3', sender: 'System', senderType: 'system', message: 'Ticket escalated to Senior CS Agent for NAV reconciliation review.', timestamp: '2026-02-19T09:00:00' },
    ],
  },
  {
    id: 'TKT-1002',
    clientId: 'cli-102',
    clientName: 'Meena Sundar',
    subject: 'KYC document re-verification required',
    description: 'SEBI mandate requires updated KYC for investments above 50 lakhs. Client needs to submit fresh documents.',
    category: 'kyc',
    priority: 'medium',
    status: 'awaiting-client',
    assignedTo: 'emp-004',
    assignedToName: 'Deepa Ramanathan',
    createdDate: '2026-02-15T11:00:00',
    updatedDate: '2026-02-19T16:30:00',
    channel: 'whatsapp',
    messages: [
      { id: 'msg-1002-1', sender: 'Deepa Ramanathan', senderType: 'agent', message: 'Dear Mrs. Sundar, as per the latest SEBI circular, we need your updated PAN, Aadhaar, and a recent bank statement for re-verification. Kindly upload the same on the portal or WhatsApp them to us.', timestamp: '2026-02-15T11:00:00' },
      { id: 'msg-1002-2', sender: 'Meena Sundar', senderType: 'client', message: 'I will send the documents by this weekend. Can you send me the exact list of documents needed?', timestamp: '2026-02-16T09:20:00' },
      { id: 'msg-1002-3', sender: 'Deepa Ramanathan', senderType: 'agent', message: 'Sure! You will need: 1) PAN Card copy, 2) Aadhaar Card (front & back), 3) Latest 3 months bank statement, 4) Passport-size photograph. You can upload these directly on the investor portal under "My Documents" section.', timestamp: '2026-02-16T09:45:00' },
    ],
  },
  {
    id: 'TKT-1003',
    clientId: 'cli-103',
    clientName: 'Vikram Bhat',
    subject: 'Investment redemption process query',
    description: 'HNI client wants to understand the partial redemption process for AIF Category II fund.',
    category: 'investment',
    priority: 'high',
    status: 'open',
    assignedTo: 'emp-002',
    assignedToName: 'Priya Venkatesh',
    createdDate: '2026-02-20T10:00:00',
    updatedDate: '2026-02-20T10:00:00',
    channel: 'call',
    messages: [
      { id: 'msg-1003-1', sender: 'Vikram Bhat', senderType: 'client', message: 'I want to redeem 30% of my investment in GHL Real Estate Growth Fund. What is the process and how long will it take?', timestamp: '2026-02-20T10:00:00' },
      { id: 'msg-1003-2', sender: 'Priya Venkatesh', senderType: 'agent', message: 'Good morning Mr. Bhat. Partial redemption for AIF Cat II requires a formal written request, and the processing time is typically 30-45 business days as per the fund terms. I will email you the redemption form and the detailed process document.', timestamp: '2026-02-20T10:20:00' },
    ],
  },
  {
    id: 'TKT-1004',
    clientId: 'cli-104',
    clientName: 'Anitha Ramachandran',
    subject: 'Unable to login to investor portal',
    description: 'Client reports a 403 error when trying to access the investor portal after password reset.',
    category: 'technical',
    priority: 'medium',
    status: 'resolved',
    assignedTo: 'emp-005',
    assignedToName: 'Manoj Kumar Pillai',
    createdDate: '2026-02-14T08:30:00',
    updatedDate: '2026-02-14T12:00:00',
    resolvedDate: '2026-02-14T12:00:00',
    channel: 'chat',
    csatScore: 5,
    messages: [
      { id: 'msg-1004-1', sender: 'Anitha Ramachandran', senderType: 'client', message: 'I reset my password but now I am getting a 403 error. I have tried multiple browsers. Please help urgently.', timestamp: '2026-02-14T08:30:00' },
      { id: 'msg-1004-2', sender: 'Manoj Kumar Pillai', senderType: 'agent', message: 'Apologies for the inconvenience, Mrs. Ramachandran. This seems to be a cache issue. Please try clearing your browser cookies and cache, then retry. If the issue persists, I will reset your session from our end.', timestamp: '2026-02-14T08:45:00' },
      { id: 'msg-1004-3', sender: 'Anitha Ramachandran', senderType: 'client', message: 'Clearing the cache worked. Thank you for the quick resolution!', timestamp: '2026-02-14T09:10:00' },
    ],
  },
  {
    id: 'TKT-1005',
    clientId: 'cli-105',
    clientName: 'Senthil Murugan',
    subject: 'TDS certificate request for FY 2025-26',
    description: 'Client is requesting Form 16A / TDS certificate for filing income tax returns.',
    category: 'documents',
    priority: 'low',
    status: 'awaiting-internal',
    assignedTo: 'emp-003',
    assignedToName: 'Karthik Subramanian',
    createdDate: '2026-02-17T14:00:00',
    updatedDate: '2026-02-19T11:00:00',
    channel: 'email',
    messages: [
      { id: 'msg-1005-1', sender: 'Senthil Murugan', senderType: 'client', message: 'Kindly share the TDS certificate (Form 16A) for FY 2025-26 for my investments in GHL AIF. My CA needs it for tax filing.', timestamp: '2026-02-17T14:00:00' },
      { id: 'msg-1005-2', sender: 'Karthik Subramanian', senderType: 'agent', message: 'Thank you for your request, Mr. Murugan. I have forwarded this to our finance team. Form 16A is typically generated by end of May. We will share it at the earliest once available.', timestamp: '2026-02-17T14:30:00' },
      { id: 'msg-1005-3', sender: 'System', senderType: 'system', message: 'Internal task created: Generate Form 16A for client Senthil Murugan (FY 2025-26). Assigned to Finance Team.', timestamp: '2026-02-17T15:00:00' },
    ],
  },
  {
    id: 'TKT-1006',
    clientId: 'cli-106',
    clientName: 'Padmavathi Krishnan',
    subject: 'Complaint about delayed quarterly report',
    description: 'Investor has not received the Q3 2025-26 quarterly report that was due in January.',
    category: 'complaint',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'emp-002',
    assignedToName: 'Priya Venkatesh',
    createdDate: '2026-02-12T16:00:00',
    updatedDate: '2026-02-20T09:00:00',
    channel: 'call',
    escalationLevel: 2,
    messages: [
      { id: 'msg-1006-1', sender: 'Padmavathi Krishnan', senderType: 'client', message: 'I have not received my Q3 report. It is already mid-February. This is unacceptable and I want to know the reason for the delay.', timestamp: '2026-02-12T16:00:00' },
      { id: 'msg-1006-2', sender: 'Priya Venkatesh', senderType: 'agent', message: 'We sincerely apologize for the delay, Mrs. Krishnan. The Q3 reports are being finalized after the auditor review. We expect to dispatch them by 25th February. I will personally ensure you receive it on priority.', timestamp: '2026-02-12T16:30:00' },
      { id: 'msg-1006-3', sender: 'System', senderType: 'system', message: 'Ticket escalated to CS Lead. SLA breach alert: Q3 report delivery delayed beyond 45 days.', timestamp: '2026-02-18T09:00:00' },
    ],
  },
  {
    id: 'TKT-1007',
    clientId: 'cli-107',
    clientName: 'Gopal Narayanan',
    subject: 'New investment enquiry - AIF Category I',
    description: 'Prospective investor from Coimbatore interested in sustainable infrastructure fund.',
    category: 'investment',
    priority: 'medium',
    status: 'open',
    assignedTo: 'emp-005',
    assignedToName: 'Manoj Kumar Pillai',
    createdDate: '2026-02-21T09:00:00',
    updatedDate: '2026-02-21T09:00:00',
    channel: 'whatsapp',
    messages: [
      { id: 'msg-1007-1', sender: 'Gopal Narayanan', senderType: 'client', message: 'Hello, I was referred by Mr. Iyer. I am interested in investing in AIF Category I sustainable infrastructure. Can someone explain the minimum investment and expected returns?', timestamp: '2026-02-21T09:00:00' },
      { id: 'msg-1007-2', sender: 'Manoj Kumar Pillai', senderType: 'agent', message: 'Welcome to GHL India Ventures, Mr. Narayanan! Thank you for your interest. Our AIF Cat I Sustainable Infrastructure Fund has a minimum commitment of INR 1 Crore. I will share the detailed PPM and factsheet via email. May I have your email ID?', timestamp: '2026-02-21T09:15:00' },
    ],
  },
  {
    id: 'TKT-1008',
    clientId: 'cli-108',
    clientName: 'Revathi Subramaniam',
    subject: 'Nominee update request',
    description: 'Client wants to update the nominee details for her AIF investments.',
    category: 'account',
    priority: 'low',
    status: 'closed',
    assignedTo: 'emp-004',
    assignedToName: 'Deepa Ramanathan',
    createdDate: '2026-02-05T10:30:00',
    updatedDate: '2026-02-10T14:00:00',
    resolvedDate: '2026-02-10T14:00:00',
    channel: 'email',
    csatScore: 4,
    messages: [
      { id: 'msg-1008-1', sender: 'Revathi Subramaniam', senderType: 'client', message: 'I need to change my nominee from my husband to my daughter. Please let me know the process.', timestamp: '2026-02-05T10:30:00' },
      { id: 'msg-1008-2', sender: 'Deepa Ramanathan', senderType: 'agent', message: 'Sure, Mrs. Subramaniam. Please fill out the enclosed Nominee Change Form and attach a self-attested copy of your daughter\'s Aadhaar. You can email the signed form or upload it on the portal.', timestamp: '2026-02-05T11:00:00' },
      { id: 'msg-1008-3', sender: 'Revathi Subramaniam', senderType: 'client', message: 'I have uploaded the form and documents on the portal. Please process the change.', timestamp: '2026-02-08T15:00:00' },
    ],
  },
]

// ── 8. Client Interactions ──────────────────────────────────────
export const CLIENT_INTERACTIONS_DATA: ClientInteraction[] = [
  {
    id: 'int-001',
    clientId: 'cli-101',
    clientName: 'Raghunath Iyer',
    channel: 'call',
    direction: 'inbound',
    subject: 'NAV clarification follow-up',
    summary: 'Client called to follow up on NAV discrepancy ticket. Explained T+1 lag in portal updates.',
    agentId: 'emp-003',
    agentName: 'Karthik Subramanian',
    startTime: '2026-02-20T10:30:00',
    endTime: '2026-02-20T10:42:00',
    duration: 12,
    status: 'completed',
    sentiment: 'neutral',
    csatScore: 4,
    ticketId: 'TKT-1001',
  },
  {
    id: 'int-002',
    clientId: 'cli-105',
    clientName: 'Senthil Murugan',
    channel: 'email',
    direction: 'outbound',
    subject: 'TDS certificate status update',
    summary: 'Sent email update to client regarding Form 16A generation timeline.',
    agentId: 'emp-003',
    agentName: 'Karthik Subramanian',
    startTime: '2026-02-19T14:00:00',
    status: 'completed',
    sentiment: 'neutral',
    ticketId: 'TKT-1005',
  },
  {
    id: 'int-003',
    clientId: 'cli-109',
    clientName: 'Ashok Venkataraman',
    channel: 'video',
    direction: 'outbound',
    subject: 'Quarterly portfolio review',
    summary: 'Conducted quarterly portfolio review via video call. Client is pleased with 14.2% returns. Discussed new Cat II fund launch.',
    agentId: 'emp-006',
    agentName: 'Lakshmi Narayanan',
    startTime: '2026-02-20T11:00:00',
    endTime: '2026-02-20T11:45:00',
    duration: 45,
    status: 'completed',
    sentiment: 'positive',
    csatScore: 5,
  },
  {
    id: 'int-004',
    clientId: 'cli-102',
    clientName: 'Meena Sundar',
    channel: 'whatsapp',
    direction: 'inbound',
    subject: 'KYC document submission confirmation',
    summary: 'Client sent KYC documents via WhatsApp. Acknowledged receipt and confirmed they will be processed in 48 hours.',
    agentId: 'emp-004',
    agentName: 'Deepa Ramanathan',
    startTime: '2026-02-20T15:30:00',
    endTime: '2026-02-20T15:38:00',
    duration: 8,
    status: 'completed',
    sentiment: 'positive',
    ticketId: 'TKT-1002',
  },
  {
    id: 'int-005',
    clientId: 'cli-106',
    clientName: 'Padmavathi Krishnan',
    channel: 'call',
    direction: 'inbound',
    subject: 'Escalation regarding delayed Q3 report',
    summary: 'Client called in an agitated state about delayed quarterly report. Assured priority dispatch by Feb 25.',
    agentId: 'emp-002',
    agentName: 'Priya Venkatesh',
    startTime: '2026-02-18T10:00:00',
    endTime: '2026-02-18T10:18:00',
    duration: 18,
    status: 'completed',
    sentiment: 'negative',
    ticketId: 'TKT-1006',
  },
  {
    id: 'int-006',
    clientId: 'cli-110',
    clientName: 'Jayashree Parthasarathy',
    channel: 'chat',
    direction: 'inbound',
    subject: 'Fund fact sheet download issue',
    summary: 'Client unable to download fund fact sheet PDF. Guided her through the process and resolved.',
    agentId: 'emp-005',
    agentName: 'Manoj Kumar Pillai',
    startTime: '2026-02-20T09:00:00',
    endTime: '2026-02-20T09:12:00',
    duration: 12,
    status: 'completed',
    sentiment: 'positive',
    csatScore: 5,
  },
  {
    id: 'int-007',
    clientId: 'cli-111',
    clientName: 'Ravi Shankar Gupta',
    channel: 'telegram',
    direction: 'inbound',
    subject: 'Investment maturity query',
    summary: 'NRI client enquired about maturity date and exit load for Cat II investment made in 2023.',
    agentId: 'emp-007',
    agentName: 'Suresh Balakrishnan',
    startTime: '2026-02-19T18:30:00',
    endTime: '2026-02-19T18:50:00',
    duration: 20,
    status: 'completed',
    sentiment: 'neutral',
  },
  {
    id: 'int-008',
    clientId: 'cli-112',
    clientName: 'Kavitha Mani',
    channel: 'call',
    direction: 'outbound',
    subject: 'New fund launch introduction',
    summary: 'Proactive call to inform HNI client about the new AIF Cat II Opportunity Fund launch. Client expressed strong interest.',
    agentId: 'emp-006',
    agentName: 'Lakshmi Narayanan',
    startTime: '2026-02-21T11:30:00',
    endTime: '2026-02-21T11:52:00',
    duration: 22,
    status: 'completed',
    sentiment: 'positive',
    csatScore: 5,
  },
  {
    id: 'int-009',
    clientId: 'cli-107',
    clientName: 'Gopal Narayanan',
    channel: 'whatsapp',
    direction: 'inbound',
    subject: 'AIF enquiry from referral',
    summary: 'New prospect from Coimbatore reached out via WhatsApp after referral. Shared preliminary information.',
    agentId: 'emp-005',
    agentName: 'Manoj Kumar Pillai',
    startTime: '2026-02-21T09:00:00',
    endTime: '2026-02-21T09:18:00',
    duration: 18,
    status: 'completed',
    sentiment: 'positive',
    ticketId: 'TKT-1007',
  },
  {
    id: 'int-010',
    clientId: 'cli-113',
    clientName: 'Prakash Natarajan',
    channel: 'video',
    direction: 'outbound',
    subject: 'Due diligence walkthrough for new investment',
    summary: 'Virtual due diligence session with prospective HNI investor. Shared project details and financials for upcoming real estate fund.',
    agentId: 'emp-007',
    agentName: 'Suresh Balakrishnan',
    startTime: '2026-02-20T15:00:00',
    endTime: '2026-02-20T15:55:00',
    duration: 55,
    status: 'completed',
    sentiment: 'positive',
    csatScore: 4,
  },
  {
    id: 'int-011',
    clientId: 'cli-114',
    clientName: 'Sundari Rajendran',
    channel: 'chat',
    direction: 'inbound',
    subject: 'Password reset assistance',
    summary: 'Client requested help resetting portal password. Sent OTP and guided through process.',
    agentId: 'emp-003',
    agentName: 'Karthik Subramanian',
    startTime: '2026-02-21T08:45:00',
    endTime: '2026-02-21T08:52:00',
    duration: 7,
    status: 'completed',
    sentiment: 'neutral',
    csatScore: 4,
  },
  {
    id: 'int-012',
    clientId: 'cli-115',
    clientName: 'Mohan Lal',
    channel: 'email',
    direction: 'inbound',
    subject: 'Missed call - requested callback',
    summary: 'Client called but line was busy. Sent email requesting callback on Monday morning.',
    agentId: 'emp-005',
    agentName: 'Manoj Kumar Pillai',
    startTime: '2026-02-20T17:30:00',
    status: 'missed',
    sentiment: 'negative',
  },
]

// ── 9. Queue Data ───────────────────────────────────────────────
export const QUEUE_DATA: QueueItem[] = [
  {
    id: 'q-001',
    clientId: 'cli-116',
    clientName: 'Nagaraj Srinivasan',
    channel: 'call',
    waitTime: 180,
    priority: 'high',
    query: 'Urgent redemption request',
  },
  {
    id: 'q-002',
    clientId: 'cli-117',
    clientName: 'Vasanthi Devi',
    channel: 'chat',
    waitTime: 45,
    priority: 'medium',
    query: 'NAV update question',
  },
  {
    id: 'q-003',
    clientId: 'cli-118',
    clientName: 'Kiran Kumar Reddy',
    channel: 'whatsapp',
    waitTime: 120,
    priority: 'medium',
    query: 'Document upload help needed',
  },
  {
    id: 'q-004',
    clientId: 'cli-119',
    clientName: 'Saraswathi Amma',
    channel: 'email',
    waitTime: 300,
    priority: 'low',
    query: 'General enquiry about new fund scheme',
  },
  {
    id: 'q-005',
    clientId: 'cli-120',
    clientName: 'Abdul Rahman',
    channel: 'call',
    waitTime: 90,
    priority: 'critical',
    query: 'Compliance issue with investment declaration',
  },
  {
    id: 'q-006',
    clientName: 'Unknown Caller',
    channel: 'call',
    waitTime: 60,
    priority: 'low',
    query: 'Pre-sales enquiry',
  },
]

// ── 10. Tasks ───────────────────────────────────────────────────
export const TASKS_DATA: StaffTask[] = [
  {
    id: 'task-001',
    title: 'Follow up with Raghunath Iyer on NAV discrepancy',
    description: 'Confirm with fund accounting team and share final reconciliation report with client.',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'emp-003',
    assignedBy: 'Arvind Krishnamurthy',
    dueDate: '2026-02-22',
    createdDate: '2026-02-19',
    linkedClient: 'Raghunath Iyer',
    linkedTicket: 'TKT-1001',
    source: 'escalation',
    tags: ['nav', 'client-follow-up'],
  },
  {
    id: 'task-002',
    title: 'Prepare Q3 investor report mailing list',
    description: 'Compile the list of all active investors for Q3 report dispatch. Coordinate with operations for printing.',
    priority: 'urgent',
    status: 'todo',
    assignedTo: 'emp-013',
    assignedBy: 'Arvind Krishnamurthy',
    dueDate: '2026-02-24',
    createdDate: '2026-02-20',
    source: 'admin',
    tags: ['quarterly-report', 'operations'],
  },
  {
    id: 'task-003',
    title: 'Complete KYC verification for 5 pending clients',
    description: 'Review and verify submitted KYC documents for clients who submitted in the last 7 days.',
    priority: 'high',
    status: 'in-progress',
    assignedTo: 'emp-012',
    assignedBy: 'Arvind Krishnamurthy',
    dueDate: '2026-02-23',
    createdDate: '2026-02-18',
    source: 'auto',
    tags: ['kyc', 'compliance'],
  },
  {
    id: 'task-004',
    title: 'Update CRM with new prospect details from Coimbatore event',
    description: 'Enter all 12 new prospect cards collected at the Coimbatore investor meet into the CRM system.',
    priority: 'normal',
    status: 'todo',
    assignedTo: 'emp-009',
    assignedBy: 'Rajesh Chandrasekaran',
    dueDate: '2026-02-25',
    createdDate: '2026-02-20',
    source: 'manual',
    tags: ['crm', 'prospects', 'field-event'],
  },
  {
    id: 'task-005',
    title: 'Schedule site visits for Bangalore prospects',
    description: 'Arrange site visits for 3 Bangalore-based HNI prospects to OMR development project.',
    priority: 'high',
    status: 'blocked',
    assignedTo: 'emp-010',
    assignedBy: 'Rajesh Chandrasekaran',
    dueDate: '2026-02-26',
    createdDate: '2026-02-19',
    source: 'manual',
    tags: ['site-visit', 'bangalore', 'prospects'],
  },
  {
    id: 'task-006',
    title: 'Send CSAT survey to resolved ticket clients',
    description: 'Trigger CSAT survey emails for all tickets resolved in the past week (7 tickets).',
    priority: 'normal',
    status: 'done',
    assignedTo: 'emp-005',
    assignedBy: 'Priya Venkatesh',
    dueDate: '2026-02-20',
    createdDate: '2026-02-18',
    source: 'auto',
    tags: ['csat', 'survey'],
  },
  {
    id: 'task-007',
    title: 'Review and approve field expense claims for January',
    description: 'Audit and approve pending field expense reimbursement requests from the field sales team.',
    priority: 'normal',
    status: 'in-progress',
    assignedTo: 'emp-008',
    assignedBy: 'Rajesh Venkataraman',
    dueDate: '2026-02-22',
    createdDate: '2026-02-15',
    source: 'admin',
    tags: ['expenses', 'field-sales', 'approval'],
  },
  {
    id: 'task-008',
    title: 'Prepare training material for new SEBI AIF circular',
    description: 'Create internal training deck on the latest SEBI circular regarding AIF reporting and compliance requirements.',
    priority: 'low',
    status: 'todo',
    assignedTo: 'emp-002',
    assignedBy: 'Arvind Krishnamurthy',
    dueDate: '2026-02-28',
    createdDate: '2026-02-21',
    source: 'admin',
    tags: ['training', 'sebi', 'compliance'],
  },
]

// ── 11. Field Check-Ins ─────────────────────────────────────────
export const FIELD_CHECKINS_DATA: FieldCheckIn[] = [
  {
    id: 'chk-001',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    location: 'DLF IT Park, Taramani, Chennai',
    coordinates: { lat: 12.9866, lng: 80.2442 },
    type: 'client-meeting',
    linkedEntity: 'Prakash Natarajan',
    checkInTime: '2026-02-20T10:00:00',
    checkOutTime: '2026-02-20T11:30:00',
    duration: 90,
    note: 'Met with prospective HNI investor. Discussed AIF Cat II Real Estate Fund.',
    outcome: 'Prospect interested, follow-up scheduled for next week',
  },
  {
    id: 'chk-002',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    location: 'Prestige Lakeside Habitat, Thoraipakkam, Chennai',
    coordinates: { lat: 12.9352, lng: 80.2283 },
    type: 'site',
    linkedEntity: 'GHL Lakeside Project',
    checkInTime: '2026-02-20T09:00:00',
    checkOutTime: '2026-02-20T12:00:00',
    duration: 180,
    selfieUrl: '/mock/selfie-chk002.jpg',
    note: 'Site inspection for Phase 2 construction. 3rd floor slab completed.',
    outcome: 'Construction on track. 62% complete.',
  },
  {
    id: 'chk-003',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    location: 'ITC Grand Chola, Guindy, Chennai',
    coordinates: { lat: 13.0105, lng: 80.2127 },
    type: 'investor-event',
    linkedEntity: 'GHL Q3 Investor Meet',
    checkInTime: '2026-02-19T17:00:00',
    checkOutTime: '2026-02-19T21:00:00',
    duration: 240,
    note: 'Quarterly investor meet. 45 investors attended. Good engagement.',
    outcome: '8 new prospects identified, 3 existing investors interested in top-up',
  },
  {
    id: 'chk-004',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    location: 'Manyata Tech Park, Hebbal, Bangalore',
    coordinates: { lat: 13.0467, lng: 77.6210 },
    type: 'client-meeting',
    linkedEntity: 'Ravi Shankar Gupta',
    checkInTime: '2026-02-19T11:00:00',
    checkOutTime: '2026-02-19T12:15:00',
    duration: 75,
    note: 'Portfolio review meeting with NRI client visiting from Dubai.',
    outcome: 'Client satisfied with returns. Exploring additional investment in Cat I fund.',
  },
  {
    id: 'chk-005',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    location: 'UB City, Vittal Mallya Road, Bangalore',
    coordinates: { lat: 12.9716, lng: 77.5965 },
    type: 'client-meeting',
    linkedEntity: 'Jayashree Parthasarathy',
    checkInTime: '2026-02-18T15:00:00',
    checkOutTime: '2026-02-18T16:00:00',
    duration: 60,
    note: 'Introductory meeting with HNI prospect referred by existing investor.',
    outcome: 'Prospect keen to invest 2 Cr in real estate AIF. Site visit to be arranged.',
  },
  {
    id: 'chk-006',
    staffId: 'emp-008',
    staffName: 'Rajesh Chandrasekaran',
    location: 'GHL Anna Nagar Branch Office, Chennai',
    coordinates: { lat: 13.0850, lng: 80.2101 },
    type: 'branch',
    checkInTime: '2026-02-21T09:00:00',
    checkOutTime: '2026-02-21T13:00:00',
    duration: 240,
    note: 'Weekly team review meeting with field sales executives.',
    outcome: 'Reviewed pipeline, set targets for March. 2 deals expected to close this week.',
  },
  {
    id: 'chk-007',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    location: 'Casagrand Irene, Manapakkam, Chennai',
    coordinates: { lat: 13.0145, lng: 80.1680 },
    type: 'site',
    linkedEntity: 'GHL Manapakkam Phase I',
    checkInTime: '2026-02-18T10:00:00',
    checkOutTime: '2026-02-18T13:00:00',
    duration: 180,
    selfieUrl: '/mock/selfie-chk007.jpg',
    note: 'Due diligence inspection for potential new project investment.',
    outcome: 'Project meets criteria. Report submitted for investment committee review.',
  },
  {
    id: 'chk-008',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    location: 'Sobha Ltd Developer Office, OMR, Chennai',
    coordinates: { lat: 12.9081, lng: 80.2271 },
    type: 'developer-office',
    linkedEntity: 'Sobha Ltd',
    checkInTime: '2026-02-17T14:00:00',
    checkOutTime: '2026-02-17T15:30:00',
    duration: 90,
    note: 'Meeting with developer team to discuss co-investment opportunity in upcoming project.',
    outcome: 'MOU discussion initiated. Legal team to review terms.',
  },
]

// ── 12. Site Visits ─────────────────────────────────────────────
export const SITE_VISITS_DATA: SiteVisit[] = [
  {
    id: 'sv-001',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    siteName: 'GHL Lakeside Project - Phase 2',
    address: 'Plot No. 45, Thoraipakkam Main Road, Thoraipakkam, Chennai 600097',
    coordinates: { lat: 12.9352, lng: 80.2283 },
    purpose: 'construction-inspection',
    scheduledDate: '2026-02-20',
    scheduledTime: '09:00',
    status: 'completed',
    duration: 180,
    mediaCount: 24,
    reportStatus: 'submitted',
    notes: 'Phase 2 third floor slab poured. Quality is excellent. Minor rebar spacing issue flagged in Block C.',
    progressPercent: 62,
  },
  {
    id: 'sv-002',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    siteName: 'GHL ECR Premium Villas',
    address: '23/4, East Coast Road, Injambakkam, Chennai 600115',
    coordinates: { lat: 12.9151, lng: 80.2540 },
    purpose: 'investor-tour',
    scheduledDate: '2026-02-22',
    scheduledTime: '10:00',
    status: 'scheduled',
    linkedClient: 'Vikram Bhat',
    notes: 'HNI investor tour. Arrange transport from Adyar. Lunch at site guest house.',
  },
  {
    id: 'sv-003',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    siteName: 'GHL Whitefield Tech Hub',
    address: 'Survey No. 78, ITPL Road, Whitefield, Bangalore 560066',
    coordinates: { lat: 12.9698, lng: 77.7500 },
    purpose: 'prospect-meeting',
    scheduledDate: '2026-02-23',
    scheduledTime: '11:00',
    status: 'scheduled',
    linkedClient: 'Ravi Shankar Gupta',
    notes: 'NRI prospect wants to see the commercial tech park development before committing.',
  },
  {
    id: 'sv-004',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    siteName: 'GHL Manapakkam Phase I',
    address: 'No. 12, Mount Poonamallee Road, Manapakkam, Chennai 600089',
    coordinates: { lat: 13.0145, lng: 80.1680 },
    purpose: 'due-diligence',
    scheduledDate: '2026-02-18',
    scheduledTime: '10:00',
    status: 'completed',
    duration: 180,
    mediaCount: 32,
    reportStatus: 'reviewed',
    notes: 'Comprehensive due diligence for new project investment. Soil test reports verified. Legal title clear.',
    progressPercent: 15,
  },
  {
    id: 'sv-005',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    siteName: 'GHL OMR Business Park',
    address: 'Plot 56-58, Rajiv Gandhi Salai (OMR), Sholinganallur, Chennai 600119',
    coordinates: { lat: 12.9010, lng: 80.2279 },
    purpose: 'construction-inspection',
    scheduledDate: '2026-02-16',
    scheduledTime: '09:30',
    status: 'completed',
    duration: 150,
    mediaCount: 18,
    reportStatus: 'submitted',
    notes: 'Commercial office space project. Foundation work complete. First floor columns being erected.',
    progressPercent: 28,
  },
  {
    id: 'sv-006',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    siteName: 'GHL Koramangala Residency',
    address: '4th Block, 80 Feet Road, Koramangala, Bangalore 560034',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    purpose: 'photography',
    scheduledDate: '2026-02-24',
    scheduledTime: '07:00',
    status: 'scheduled',
    notes: 'Professional photography session for marketing collateral. Early morning for best lighting.',
  },
  {
    id: 'sv-007',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    siteName: 'GHL Perungudi Apartments',
    address: 'No. 8, Perungudi Main Road, Perungudi, Chennai 600096',
    coordinates: { lat: 12.9601, lng: 80.2416 },
    purpose: 'construction-inspection',
    scheduledDate: '2026-02-14',
    scheduledTime: '10:00',
    status: 'completed',
    duration: 120,
    mediaCount: 15,
    reportStatus: 'reviewed',
    notes: 'Apartment project nearing completion. Finishing work in progress. Occupancy expected April 2026.',
    progressPercent: 88,
  },
  {
    id: 'sv-008',
    staffId: 'emp-008',
    staffName: 'Rajesh Chandrasekaran',
    siteName: 'GHL Velachery Commercial Hub',
    address: '100 Feet Road, Velachery, Chennai 600042',
    coordinates: { lat: 12.9815, lng: 80.2180 },
    purpose: 'developer-meeting',
    scheduledDate: '2026-02-21',
    scheduledTime: '14:00',
    status: 'completed',
    duration: 90,
    notes: 'Meeting with JV developer partner to finalize Phase 2 terms.',
    reportStatus: 'draft',
  },
  {
    id: 'sv-009',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    siteName: 'GHL Anna Nagar Premium Plots',
    address: '3rd Avenue, Anna Nagar West, Chennai 600040',
    coordinates: { lat: 13.0850, lng: 80.2107 },
    purpose: 'investor-tour',
    scheduledDate: '2026-02-12',
    scheduledTime: '11:00',
    status: 'completed',
    duration: 60,
    linkedClient: 'Gopal Narayanan',
    notes: 'Tour for Coimbatore-based prospect. Very impressed with location and layout plan.',
  },
  {
    id: 'sv-010',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    siteName: 'GHL Electronic City Tech Campus',
    address: 'Phase 1, Electronic City, Hosur Road, Bangalore 560100',
    coordinates: { lat: 12.8399, lng: 77.6770 },
    purpose: 'due-diligence',
    scheduledDate: '2026-02-25',
    scheduledTime: '09:00',
    status: 'scheduled',
    notes: 'Initial site assessment for potential new tech campus investment in Bangalore market.',
  },
]

// ── 13. Field Prospects ─────────────────────────────────────────
export const FIELD_PROSPECTS_DATA: FieldProspect[] = [
  {
    id: 'fp-001',
    name: 'Prakash Natarajan',
    company: 'Natarajan Exports Pvt Ltd',
    phone: '+91 98840 11223',
    email: 'prakash@natarajanexports.com',
    designation: 'Managing Director',
    investmentInterest: 'AIF Category II - Real Estate Growth Fund',
    meetingDate: '2026-02-20',
    outcome: 'hot',
    dealPotential: 20000000,
    probability: 75,
    stage: 'proposal-sent',
    nextAction: 'Follow up on PPM review and schedule legal discussion',
    nextActionDate: '2026-02-25',
    assignedTo: 'emp-009',
    notes: 'MD of export company. Very knowledgeable about real estate. Wants tax-efficient structure.',
    location: 'Chennai',
  },
  {
    id: 'fp-002',
    name: 'Dr. Kamala Haasan',
    company: 'Haasan Medical Centre',
    phone: '+91 99001 22334',
    email: 'kamala.h@haasanmedical.in',
    designation: 'Chief Medical Director',
    investmentInterest: 'AIF Category I - Sustainable Infrastructure',
    meetingDate: '2026-02-18',
    outcome: 'warm',
    dealPotential: 15000000,
    probability: 50,
    stage: 'site-visit-done',
    nextAction: 'Send detailed financial projections and ESG impact report',
    nextActionDate: '2026-02-24',
    assignedTo: 'emp-010',
    notes: 'Interested in sustainable and ESG-compliant investments. First-time AIF investor.',
    location: 'Bangalore',
  },
  {
    id: 'fp-003',
    name: 'Sundaram Ramalingam',
    company: 'SR Textiles',
    phone: '+91 98765 33445',
    designation: 'Chairman',
    investmentInterest: 'AIF Category II - Real Estate Growth Fund',
    meetingDate: '2026-02-15',
    outcome: 'follow-up',
    dealPotential: 50000000,
    probability: 40,
    stage: 'negotiation',
    nextAction: 'Arrange meeting with fund manager for detailed Q&A',
    nextActionDate: '2026-02-27',
    assignedTo: 'emp-008',
    notes: 'Ultra HNI from Coimbatore textile family. Has prior AIF experience with other AMCs. Price-sensitive on fees.',
    location: 'Chennai',
  },
  {
    id: 'fp-004',
    name: 'Meera Nair',
    phone: '+91 98456 44556',
    email: 'meera.nair@outlook.com',
    designation: 'Retired IAS Officer',
    investmentInterest: 'AIF Category III - Long-Short Equity',
    meetingDate: '2026-02-10',
    outcome: 'cold',
    dealPotential: 10000000,
    probability: 20,
    stage: 'initial-contact',
    nextAction: 'Send introductory mailer and risk-adjusted return comparison',
    nextActionDate: '2026-03-01',
    assignedTo: 'emp-009',
    notes: 'Conservative investor. Concerned about lock-in period. Prefers fixed-income products.',
    location: 'Chennai',
  },
  {
    id: 'fp-005',
    name: 'Arjun Reddy',
    company: 'Reddy Constructions',
    phone: '+91 99887 55667',
    email: 'arjun@reddyconstructions.com',
    designation: 'Director',
    investmentInterest: 'AIF Category II - Real Estate Growth Fund',
    meetingDate: '2026-02-21',
    outcome: 'hot',
    dealPotential: 30000000,
    probability: 80,
    stage: 'documents-pending',
    nextAction: 'Collect signed subscription agreement and KYC documents',
    nextActionDate: '2026-02-23',
    assignedTo: 'emp-010',
    notes: 'Construction industry background. Understands real estate well. Ready to commit once paperwork is done.',
    location: 'Bangalore',
  },
  {
    id: 'fp-006',
    name: 'Lakshmi Venkataraman',
    company: 'LV Holdings',
    phone: '+91 98123 66778',
    email: 'lakshmi@lvholdings.in',
    designation: 'Promoter',
    investmentInterest: 'AIF Category I - Infrastructure Fund',
    meetingDate: '2026-02-19',
    outcome: 'warm',
    dealPotential: 25000000,
    probability: 55,
    stage: 'proposal-sent',
    nextAction: 'Schedule call to discuss fee structure and co-investment option',
    nextActionDate: '2026-02-26',
    assignedTo: 'emp-008',
    notes: 'Family office with existing real estate portfolio. Looking to diversify into infrastructure via AIF route.',
    location: 'Chennai',
  },
  {
    id: 'fp-007',
    name: 'Rajiv Menon',
    company: 'Menon IT Solutions',
    phone: '+91 97456 77889',
    email: 'rajiv.menon@menonit.com',
    designation: 'CEO',
    investmentInterest: 'AIF Category II - Opportunity Fund',
    meetingDate: '2026-02-22',
    outcome: 'hot',
    dealPotential: 10000000,
    probability: 70,
    stage: 'site-visit-done',
    nextAction: 'Share subscription documents and arrange fund manager call',
    nextActionDate: '2026-02-24',
    assignedTo: 'emp-009',
    notes: 'Tech entrepreneur. First AIF investment. Visited OMR project site and was very impressed.',
    location: 'Chennai',
  },
  {
    id: 'fp-008',
    name: 'Preethi Srinivasan',
    phone: '+91 98234 88990',
    email: 'preethi.srini@gmail.com',
    investmentInterest: 'AIF Category I - Sustainable Infrastructure',
    meetingDate: '2026-02-14',
    outcome: 'not-interested',
    dealPotential: 10000000,
    probability: 5,
    stage: 'initial-contact',
    nextAction: 'Mark as dormant. Re-approach after 6 months with new fund launch.',
    nextActionDate: '2026-08-14',
    assignedTo: 'emp-010',
    notes: 'Not comfortable with AIF lock-in period. Prefers liquid mutual fund investments.',
    location: 'Bangalore',
  },
]

// ── 14. Field Expenses ──────────────────────────────────────────
export const FIELD_EXPENSES_DATA: FieldExpense[] = [
  {
    id: 'exp-001',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    date: '2026-02-20',
    category: 'fuel',
    amount: 850,
    description: 'Petrol for site visit to Thoraipakkam and client meeting at DLF IT Park',
    vendor: 'Indian Oil, Adyar',
    receiptUrl: '/mock/receipt-exp001.jpg',
    linkedVisit: 'sv-001',
    status: 'pending',
  },
  {
    id: 'exp-002',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    date: '2026-02-19',
    category: 'meals',
    amount: 450,
    description: 'Client lunch meeting at Manyata Tech Park food court',
    vendor: 'Mainland China, Manyata Tech Park',
    linkedVisit: 'sv-003',
    status: 'approved',
    approvedBy: 'Rajesh Chandrasekaran',
  },
  {
    id: 'exp-003',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    date: '2026-02-20',
    category: 'parking',
    amount: 150,
    description: 'Parking charges at Thoraipakkam site during construction inspection',
    linkedVisit: 'sv-001',
    status: 'approved',
    approvedBy: 'Rajesh Chandrasekaran',
  },
  {
    id: 'exp-004',
    staffId: 'emp-009',
    staffName: 'Arun Prakash',
    date: '2026-02-19',
    category: 'fuel',
    amount: 600,
    description: 'Petrol for ITC Grand Chola investor event attendance',
    vendor: 'HP Petrol Pump, Guindy',
    receiptUrl: '/mock/receipt-exp004.jpg',
    linkedVisit: 'sv-009',
    status: 'reimbursed',
    approvedBy: 'Rajesh Chandrasekaran',
  },
  {
    id: 'exp-005',
    staffId: 'emp-011',
    staffName: 'Vijay Anand',
    date: '2026-02-18',
    category: 'site-entry',
    amount: 200,
    description: 'Site entry pass and safety gear deposit at Manapakkam project',
    linkedVisit: 'sv-004',
    status: 'approved',
    approvedBy: 'Rajesh Chandrasekaran',
  },
  {
    id: 'exp-006',
    staffId: 'emp-010',
    staffName: 'Divya Shanmugam',
    date: '2026-02-18',
    category: 'meals',
    amount: 350,
    description: 'Coffee and snacks during client meeting at UB City',
    vendor: 'Starbucks, UB City',
    status: 'rejected',
    approvedBy: 'Rajesh Chandrasekaran',
  },
]

// ── 15. Staff AI Tools ──────────────────────────────────────────
export const STAFF_AI_TOOLS: StaffAITool[] = [
  // CS-focused AI Tools (12)
  {
    id: 'ai-001',
    name: 'Smart Reply Generator',
    description: 'Generates contextual, professional reply suggestions for client queries across email, chat, and WhatsApp channels based on conversation history and knowledge base.',
    icon: 'MessageSquareText',
    category: 'cs-assist',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'relationship-manager'],
  },
  {
    id: 'ai-002',
    name: 'Sentiment Analyzer',
    description: 'Real-time analysis of client sentiment during calls and chats. Alerts agents when negative sentiment is detected and suggests de-escalation strategies.',
    icon: 'Heart',
    category: 'quality',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent'],
  },
  {
    id: 'ai-003',
    name: 'Ticket Auto-Classifier',
    description: 'Automatically categorizes and prioritizes incoming tickets based on content analysis, client tier, and historical patterns.',
    icon: 'Tags',
    category: 'automation',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent'],
  },
  {
    id: 'ai-004',
    name: 'Knowledge Base Search',
    description: 'AI-powered semantic search across internal knowledge base, past tickets, and regulatory documents to find relevant answers instantly.',
    icon: 'BookOpen',
    category: 'cs-assist',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'relationship-manager', 'kyc-officer'],
  },
  {
    id: 'ai-005',
    name: 'Call Transcription & Summary',
    description: 'Automatic transcription of client calls with AI-generated summaries, action items, and key discussion points extraction.',
    icon: 'FileAudio',
    category: 'automation',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'relationship-manager'],
  },
  {
    id: 'ai-006',
    name: 'CSAT Predictor',
    description: 'Predicts likely CSAT score based on interaction analysis and alerts agents to take corrective action before ticket closure.',
    icon: 'TrendingUp',
    category: 'analytics',
    status: 'beta',
    forRoles: ['cs-lead', 'senior-cs-agent'],
  },
  {
    id: 'ai-007',
    name: 'Compliance Checker',
    description: 'Scans agent responses for SEBI, AIF, and KYC compliance. Flags potential regulatory issues before messages are sent to clients.',
    icon: 'ShieldCheck',
    category: 'compliance',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'kyc-officer', 'relationship-manager'],
  },
  {
    id: 'ai-008',
    name: 'Escalation Predictor',
    description: 'Identifies tickets likely to escalate based on client history, issue complexity, and response patterns. Recommends proactive actions.',
    icon: 'AlertTriangle',
    category: 'analytics',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent'],
  },
  {
    id: 'ai-009',
    name: 'Client 360 Insights',
    description: 'Consolidated view of client history, investment portfolio, past interactions, sentiment trends, and predicted needs for personalized service.',
    icon: 'UserCircle',
    category: 'analytics',
    status: 'active',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'relationship-manager'],
  },
  {
    id: 'ai-010',
    name: 'Queue Optimizer',
    description: 'AI-driven queue management that routes tickets to the best-suited agent based on skills, workload, language, and client tier.',
    icon: 'GitBranch',
    category: 'automation',
    status: 'active',
    forRoles: ['cs-lead'],
  },
  {
    id: 'ai-011',
    name: 'KYC Document Verifier',
    description: 'Automated verification of uploaded KYC documents (PAN, Aadhaar, bank statements) using OCR and cross-referencing with government databases.',
    icon: 'ScanSearch',
    category: 'compliance',
    status: 'active',
    forRoles: ['kyc-officer', 'cs-lead', 'senior-cs-agent', 'operations-executive'],
  },
  {
    id: 'ai-012',
    name: 'Multilingual Translator',
    description: 'Real-time translation for client communications across Tamil, Hindi, Telugu, Kannada, and Malayalam with domain-specific financial vocabulary.',
    icon: 'Languages',
    category: 'cs-assist',
    status: 'beta',
    forRoles: ['cs-lead', 'senior-cs-agent', 'cs-agent', 'relationship-manager', 'field-sales-executive'],
  },
  // Field-focused AI Tools (8)
  {
    id: 'ai-013',
    name: 'Route Optimizer',
    description: 'Plans the most efficient travel route for multiple site visits and client meetings in a day, considering traffic patterns and meeting times.',
    icon: 'MapPin',
    category: 'field-ops',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'site-inspector'],
  },
  {
    id: 'ai-014',
    name: 'Site Progress Analyzer',
    description: 'Analyzes construction site photos to automatically assess progress percentage, identify issues, and generate standardized inspection reports.',
    icon: 'Camera',
    category: 'field-ops',
    status: 'beta',
    forRoles: ['site-inspector', 'field-sales-manager'],
  },
  {
    id: 'ai-015',
    name: 'Prospect Scoring Engine',
    description: 'AI-based lead scoring that ranks field prospects by conversion probability using demographic, financial, and behavioral signals.',
    icon: 'Target',
    category: 'intelligence',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'relationship-manager'],
  },
  {
    id: 'ai-016',
    name: 'Market Intelligence Brief',
    description: 'Daily AI-curated brief on local real estate market trends, competitor fund launches, regulatory updates, and investment climate for field teams.',
    icon: 'Newspaper',
    category: 'intelligence',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'relationship-manager', 'cs-lead'],
  },
  {
    id: 'ai-017',
    name: 'Expense Auto-Categorizer',
    description: 'Scans expense receipts via photo, auto-extracts vendor, amount, and category. Pre-fills expense claims for quick submission.',
    icon: 'Receipt',
    category: 'field-ops',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'site-inspector'],
  },
  {
    id: 'ai-018',
    name: 'Meeting Prep Assistant',
    description: 'Prepares a comprehensive brief before investor meetings including client profile, past interactions, investment preferences, and talking points.',
    icon: 'Briefcase',
    category: 'intelligence',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'relationship-manager'],
  },
  {
    id: 'ai-019',
    name: 'Geo-Fence Attendance',
    description: 'Validates field check-ins using GPS coordinates and geo-fencing. Automatically logs attendance for site visits within designated zones.',
    icon: 'MapPinned',
    category: 'field-ops',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'site-inspector'],
  },
  {
    id: 'ai-020',
    name: 'Pipeline Forecast',
    description: 'AI-powered pipeline forecasting that predicts monthly deal closures, revenue projections, and identifies at-risk deals needing attention.',
    icon: 'BarChart3',
    category: 'intelligence',
    status: 'active',
    forRoles: ['field-sales-manager', 'field-sales-executive', 'relationship-manager', 'cs-lead'],
  },
]

// ── 16. Knowledge Base Articles ─────────────────────────────────
export const KB_ARTICLES_DATA: KBArticle[] = [
  {
    id: 'kb-001',
    title: 'Understanding AIF Categories: Cat I, II, and III Explained',
    category: 'Investment Products',
    content: 'Alternative Investment Funds (AIFs) in India are classified into three categories by SEBI. Category I includes venture capital, social venture, and infrastructure funds that receive government incentives. Category II covers private equity, debt, and fund of funds that do not receive specific incentives or concessions. Category III comprises hedge funds and PIPE funds that employ complex trading strategies and may use leverage. Each category has different investment mandates, risk profiles, and regulatory requirements. Minimum investment for all AIFs is INR 1 Crore.',
    author: 'Arvind Krishnamurthy',
    lastUpdated: '2026-02-10',
    helpful: 45,
    notHelpful: 2,
    tags: ['aif', 'categories', 'sebi', 'investment-basics'],
  },
  {
    id: 'kb-002',
    title: 'KYC Process for AIF Investors: Step-by-Step Guide',
    category: 'KYC & Compliance',
    content: 'The KYC process for AIF investors involves: 1) Collecting PAN Card, Aadhaar, Passport (for NRIs), and proof of address. 2) CKYC registration verification. 3) Bank account verification with cancelled cheque. 4) For investments above 50 lakhs, enhanced due diligence including source of funds declaration. 5) For corporate investors, board resolution and authorized signatory documents. 6) PEP (Politically Exposed Person) screening. All documents must be self-attested and submitted within 30 days of application.',
    author: 'Meenakshi Sundaram',
    lastUpdated: '2026-02-05',
    helpful: 62,
    notHelpful: 3,
    tags: ['kyc', 'compliance', 'documents', 'ckyc', 'verification'],
  },
  {
    id: 'kb-003',
    title: 'SEBI AIF Regulations 2024-25: Key Updates and Impact',
    category: 'Regulatory',
    content: 'SEBI issued several important circulars for AIFs in 2024-25: 1) Enhanced disclosure requirements for fund performance and portfolio composition. 2) New valuation norms requiring independent valuation of unlisted securities every 6 months. 3) Stricter timeline for NAV computation and reporting (T+5 for Cat I/II, T+1 for Cat III). 4) Mandatory dematerialization of AIF units. 5) Revised concentration norms limiting single investee exposure. 6) New provisions for AIF liquidation and winding up procedures.',
    author: 'Priya Venkatesh',
    lastUpdated: '2026-01-20',
    helpful: 38,
    notHelpful: 1,
    tags: ['sebi', 'regulations', 'aif', '2024-25', 'circular'],
  },
  {
    id: 'kb-004',
    title: 'NAV Computation and Reporting: Agent Quick Reference',
    category: 'Operations',
    content: 'NAV (Net Asset Value) for GHL AIFs is computed as follows: For Cat I & II funds, NAV is calculated on a monthly basis by the fund accountant and published by the 7th of the following month. For Cat III funds, NAV is computed daily. Portal NAV updates follow a T+1 schedule. Common client queries: 1) Portal shows previous month NAV until new NAV is published. 2) Email NAV may differ from portal due to timing of update cycle. 3) Entry/exit loads are not reflected in NAV but applied during transaction processing.',
    author: 'Karthik Subramanian',
    lastUpdated: '2026-02-15',
    helpful: 51,
    notHelpful: 5,
    tags: ['nav', 'computation', 'portal', 'reporting', 'faq'],
  },
  {
    id: 'kb-005',
    title: 'Handling Investor Complaints: Escalation Matrix and SLA',
    category: 'Customer Service',
    content: 'Investor complaint handling follows a 3-tier escalation matrix. Level 1 (CS Agent): Initial response within 2 hours, resolution target 24 hours for general queries. Level 2 (Senior CS / CS Lead): Escalation for unresolved issues or high-priority clients, resolution target 48 hours. Level 3 (Management): Regulatory complaints, SEBI SCORES complaints, and issues involving financial loss, resolution target 7 business days. All complaints must be logged in the CRM with category tagging. SEBI SCORES complaints have mandatory 30-day resolution timeline.',
    author: 'Arvind Krishnamurthy',
    lastUpdated: '2026-01-30',
    helpful: 33,
    notHelpful: 0,
    tags: ['complaints', 'escalation', 'sla', 'sebi-scores', 'customer-service'],
  },
  {
    id: 'kb-006',
    title: 'Tax Implications for AIF Investors: A Quick Guide',
    category: 'Tax & Compliance',
    content: 'Tax treatment varies by AIF category. Category I & II: Pass-through taxation; income is taxed in the hands of investors. The AIF deducts TDS at 10% on income distributions. Category III: Income is taxed at fund level. Business income taxed at MMR (42.74% for domestic). Capital gains follow STCG/LTCG rules based on holding period. NRI investors face additional withholding requirements. Form 16A is issued annually by May 31. Investors should consult their tax advisors for specific situations.',
    author: 'Priya Venkatesh',
    lastUpdated: '2026-02-01',
    helpful: 56,
    notHelpful: 4,
    tags: ['tax', 'tds', 'form-16a', 'capital-gains', 'nri'],
  },
]

// ── 17. Announcements ───────────────────────────────────────────
export const ANNOUNCEMENTS_DATA: Announcement[] = [
  {
    id: 'ann-001',
    title: 'New SEBI Circular on AIF Reporting - Mandatory Training',
    content: 'SEBI has issued a new circular (SEBI/HO/AFD/AFD-POD-2/P/CIR/2026/15) regarding enhanced reporting requirements for AIFs. All CS and operations staff must complete the mandatory training module by February 28, 2026. Training is available on the internal portal under "Training > Compliance".',
    type: 'policy-update',
    postedBy: 'Arvind Krishnamurthy',
    postedDate: '2026-02-15',
    pinned: true,
    readBy: ['emp-002', 'emp-003', 'emp-005', 'emp-012'],
    department: 'Customer Success',
  },
  {
    id: 'ann-002',
    title: 'Office Timing Change for March - Holi Week',
    content: 'Please note that the office will follow reduced hours during Holi week (March 9-13). Timings will be 10:00 AM to 5:00 PM. March 10 (Holi) is a company holiday. Field teams should plan their visits accordingly.',
    type: 'general',
    postedBy: 'Sowmya Parthasarathy',
    postedDate: '2026-02-20',
    pinned: false,
    readBy: ['emp-001', 'emp-003', 'emp-008'],
  },
  {
    id: 'ann-003',
    title: 'Congratulations to Priya V - Top CSAT Score for January!',
    content: 'We are proud to announce that Priya Venkatesh has achieved the highest CSAT score of 4.9/5.0 for the month of January 2026. Her dedication to client satisfaction and quick resolution times have set a benchmark for the entire team. Well done, Priya!',
    type: 'achievement',
    postedBy: 'Rajesh Venkataraman',
    postedDate: '2026-02-05',
    pinned: false,
    readBy: ['emp-001', 'emp-003', 'emp-004', 'emp-005', 'emp-006', 'emp-012', 'emp-013'],
    department: 'Customer Success',
  },
  {
    id: 'ann-004',
    title: 'Updated Expense Reimbursement Process - Effective March 1',
    content: 'Starting March 1, 2026, all field expense claims must be submitted within 7 days of incurrence (previously 15 days). Claims must include digital receipt photos uploaded via the staff portal. Manual paper submissions will no longer be accepted. Please ensure compliance to avoid reimbursement delays.',
    type: 'process-change',
    postedBy: 'Sowmya Parthasarathy',
    postedDate: '2026-02-18',
    pinned: true,
    readBy: ['emp-008', 'emp-009', 'emp-011'],
    department: 'Field Sales',
  },
  {
    id: 'ann-005',
    title: 'Annual Day Celebration - March 22, 2026',
    content: 'GHL India Ventures Annual Day will be celebrated on March 22, 2026, at The Leela Palace, Chennai. The event includes award ceremony, team performances, and dinner. All employees and their families are invited. RSVP by March 10 via the link shared on email.',
    type: 'event',
    postedBy: 'Sowmya Parthasarathy',
    postedDate: '2026-02-21',
    pinned: false,
    readBy: ['emp-001', 'emp-002'],
  },
]

// ── 18. Training Modules ────────────────────────────────────────
export const TRAINING_MODULES_DATA: TrainingModule[] = [
  {
    id: 'trn-001',
    name: 'SEBI AIF Regulations 2026 Update',
    category: 'Compliance',
    type: 'video',
    duration: '45 mins',
    mandatory: true,
    completionStatus: 'in-progress',
    progress: 60,
    deadline: '2026-02-28',
  },
  {
    id: 'trn-002',
    name: 'Advanced KYC Verification Techniques',
    category: 'Compliance',
    type: 'document',
    duration: '30 mins',
    mandatory: true,
    completionStatus: 'completed',
    progress: 100,
    score: 92,
  },
  {
    id: 'trn-003',
    name: 'Client Communication Best Practices',
    category: 'Soft Skills',
    type: 'live-session',
    duration: '1 hour',
    mandatory: false,
    completionStatus: 'not-started',
    progress: 0,
    deadline: '2026-03-15',
  },
  {
    id: 'trn-004',
    name: 'CRM Tool Masterclass',
    category: 'Tools & Technology',
    type: 'video',
    duration: '1.5 hours',
    mandatory: false,
    completionStatus: 'completed',
    progress: 100,
    score: 85,
  },
  {
    id: 'trn-005',
    name: 'Anti-Money Laundering (AML) Essentials',
    category: 'Compliance',
    type: 'quiz',
    duration: '20 mins',
    mandatory: true,
    completionStatus: 'not-started',
    progress: 0,
    deadline: '2026-03-10',
  },
  {
    id: 'trn-006',
    name: 'Real Estate Market Analysis for Field Teams',
    category: 'Domain Knowledge',
    type: 'document',
    duration: '40 mins',
    mandatory: false,
    completionStatus: 'in-progress',
    progress: 35,
  },
]

// ── 19. Daily Motivational Quotes ───────────────────────────────
export const STAFF_DAILY_QUOTES: string[] = [
  'The secret of getting ahead is getting started. Every client interaction is an opportunity to create value.',
  'Excellence is not a destination but a continuous journey. Strive to be better today than yesterday.',
  'Great customer service is not about following rules. It is about understanding people and solving their problems with empathy.',
  'In the world of investments, trust is the currency that never depreciates. Guard it with integrity.',
  'Success in sales comes from genuinely helping people make decisions that are right for them.',
  'The best teams are not the ones that never face challenges, but the ones that face them together.',
  'Every ticket you resolve, every call you take, builds the reputation we all share.',
  'Knowledge is the foundation, but action is the builder. Apply what you learn, every single day.',
  'Your attitude determines your altitude. Approach each day with positivity and purpose.',
  'The difference between ordinary and extraordinary is that little extra effort you put in.',
]
